#!/bin/bash
#=============================================================================#
# SCRIPT:   mkjail                                                            #
# PURPOSE:  Script to create a CHROOT jail on Mac OS X                        #
# AUTHOR:   Simon Kissane                                                     #
# DATE:     6 December 2015                                                   #
# LICENSE:  Public Domain                                                     #
#=============================================================================#
function DerefSymLink() {
    [ -L "$1" ] || { echo "$1"; return; }
    local TARGET="$(readlink "$1")"
    [ -n "$TARGET" ] || { echo "$1"; return; }
    DerefSymLink "$TARGET"
}
RealExec="$(DerefSymLink "$0")"
RealExecDir="$(dirname "$RealExec")"
OriginalPWD="$(pwd -P)"
cd "$RealExecDir"

[ $# -ne 1 ] && {
    echo "usage: $0 JAILNAME"
    exit 1
}
JAILNAME="$1"
JAILDIR="/jail/$JAILNAME"

FILES="$(cat mkjail.files)"

FILECOUNT="$(echo $FILES | tr ' ' '\n' | wc -l | tr -d ' ')"

[ "$(echo "$JAILNAME" | egrep '^[A-Za-z0-9_-]+$' | wc -l)" -ne 1 ] && {
    echo "ERROR: Invalid jail name '$JAILNAME'"
    exit 1
}

echo "+ Creating jail $JAILNAME..."
mkdir -p $JAILDIR || {
    echo "ERROR: Failed to create jail directory: $JAILDIR"
    exit 1
}

echo "+ Copying required files into jail ($FILECOUNT files)..."
for file in $FILES; do
    [ -c $file ] && {
        mkdir -p "$(dirname $JAILDIR$file)" || {
            echo "ERROR: Cannot create parent dir for: $JAILDIR$file"
            exit 1
        }
        majmin="$(ls -l /dev/null | awk '{print $5, $6}' | tr -d ,)"
        if [ ! -c $JAILDIR$file ]; then
            mknod $JAILDIR$file c $majmin || {
                echo "ERROR: Failed to create device node: $JAILDIR$file"
                exit 1
            }
        fi
    }
    [ -d $file ] && {
        mkdir -p $JAILDIR$file || {
            echo "ERROR: Failed to copy directory into jail: $JAILDIR$file"
            exit 1
        }
    }
    [ -f $file ] && {
        mkdir -p "$(dirname $JAILDIR$file)" || {
            echo "ERROR: Cannot create parent dir for: $JAILDIR$file"
            exit 1
        }
        cp $file $JAILDIR$file || {
                echo "ERROR: Failed to copy file into jail: $JAILDIR$file"
                exit 1
        }
    }
done

echo "+ Entering jail $JAILNAME..."
chroot "$JAILDIR"
# vim:ts=4:sw=4:et:cc=80:
