#!/bin/bash
#=============================================================================#
# SCRIPT:   recurse                                                           #
# PURPOSE:  Recursively find dependencies of an executable/library using      #
#           otool -L                                                          #
# AUTHOR:   Simon Kissane                                                     #
# DATE:     6 December 2015                                                   #
# LICENSE:  Public Domain                                                     #
#=============================================================================#
[ $# -ne 1 ] && {
    echo "usage: $0 EXECUTABLE"
    exit 1
}
function SetUnion() {
    echo -n $(echo $1 $2 | tr ' ' '\n' | sort -u)
}
function SetSize() {
    [ -z "$*" ] && echo 0 || echo $(echo $* | tr ' ' '\n' | wc -l)
}
function SetDiff() {
    local rx="$(echo $2 | tr ' ' '\n' |  sed -e 's/^/^/;s/$/$/;s/+/\\+/g' |
                tr '\n' '|' | sed -e 's/|$//')"
    echo $1 | tr ' ' '\n' | egrep -v "$rx"
}
TOCHECK="$1"
CHECKED=""
while true; do
    TOCHECK_SIZE=$(SetSize $TOCHECK)
    [ $TOCHECK_SIZE -eq 0 ] && break
    for tc in $TOCHECK; do
        DEPS="$(otool -L $tc | fgrep -v ':' | cut '-d(' -f1)"
        DEPSNC="$(SetDiff "$DEPS" "$CHECKED")"
        TOCHECK="$TOCHECK $DEPSNC"
        CHECKED="$CHECKED $tc"
        TOCHECK="$(SetDiff "$TOCHECK" "$tc")"
    done
done
echo $CHECKED | tr ' ' '\n' | sort -u
# vim:ts=4:sw=4:et:cc=80:
